name: terraform-ci-required
on:
  pull_request:
    branches: [main]
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '.github/workflows/terraform-ci-required.yml'
  merge_group:
  workflow_dispatch:
    inputs:
      working_directory:
        description: 'Working directory for Terraform'
        required: false
        default: '.'
        type: string

permissions:
  contents: read
  security-events: write

jobs:
  terraform:
    uses: infra-ci-templates/.github/workflows/terraform-ci-template.yml@main
    with:
      working_directory: ${{ inputs.working_directory || '.' }}
      terraform_version: '1.6.0'
      enable_cost_analysis: true
      enable_security_scan: true
      enable_compliance_check: true
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      TF_STATE_RG: ${{ secrets.TF_STATE_RG }}
      TF_STATE_SA: ${{ secrets.TF_STATE_SA }}
      TF_STATE_CONTAINER: ${{ secrets.TF_STATE_CONTAINER }}
      TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}

