name: terraform-deploy-required
on:
  push:
    branches: [main]
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '.github/workflows/terraform-deploy-required.yml'
  workflow_dispatch:
    inputs:
      working_directory:
        description: 'Working directory for Terraform'
        required: false
        default: '.'
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    uses: infra-ci-templates/.github/workflows/terraform-deploy-template.yml@main
    with:
      working_directory: ${{ inputs.working_directory || '.' }}
      terraform_version: '1.6.0'
      environment: ${{ vars.ENVIRONMENT }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      PRODUCTION_APPROVERS: ${{ secrets.PRODUCTION_APPROVERS }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
